# fly.toml app configuration file generated for jsxjp-blue-frog-7046 on 2026-04-03T12:38:29+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jsxjp'
primary_region = 'nrt'

[build]
  image = 'ghcr.io/jobscale/jsxjp:main'

[[services]]
  protocol = 'tcp'
  internal_port = 3000

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'

[deploy]
  min_machines_running = 0
