#!/usr/bin/env bash
set -eu

ENV=${1:-dev}

# rm -fr node_modules package-lock.json

deploy() {
  echo
  vercel --prod -y -e ENV=${ENV}
  echo -n "check url wait ... ihttps://jsxjp.vercel.app/ ... "
  sleep 30
  [[ $(curl -I -s https://jsxjp.vercel.app/ | grep 'HTTP/2 500' | wc -l) == 0 ]] && echo "OK" && return || echo "NG"
  echo " ... retry ..."
  for i in {59..0}
  do
    echo -n "$i "
    sleep 5
  done
  deploy
}

deploy
