#!/usr/bin/env bash
set -eu

ENV=${1:-dev}

# rm -fr node_modules package-lock.json
npm ci --omit=dev

wait() {
  for i in $(seq $1 -1 0)
  do
    echo -n "$i "
    sleep 3
  done
}

check() {
  echo "check url wait ... https://jsxjp.vercel.app/ ... "
  wait 20
  [[ $(curl -I -s https://jsxjp.vercel.app/ | grep 'HTTP/2 500' | wc -l) == 0 ]] && echo "Fetch OK" && return 0
  echo "Fetch NG"
  return 1
}

deploy() {
  echo
  date
  vercel --prod -y -e ENV=${ENV}
  echo
  (check || check || check) && return 0
  echo -e "\n ... retry ..."
  deploy
}

time deploy
