#!/usr/bin/env bash
set -eu

ENV=${1:-dev}

# rm -fr node_modules package-lock.json
npm ci --omit=dev

wait() {
  for i in $(seq $1 -1 0)
  do
    echo -n "$i "
    sleep 6
  done
}

deploy() {
  echo
  vercel --prod -y -e ENV=${ENV}
  echo -n "check url wait ... https://jsxjp.vercel.app/ ... "
  wait 20
  [[ $(curl -I -s https://jsxjp.vercel.app/ | grep 'HTTP/2 500' | wc -l) == 0 ]] && echo "OK" && return || echo "NG"
  echo " ... retry ..."
  wait 40
  deploy
}

deploy
