# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm run lint
    - run: npm test

    - name: Error handling
      if: ${{ steps.error_execution.outcome == 'failure' }}
      run: |
        echo "Error handling"
        echo ${{ steps.error_execution.outcome }}
        GIP=$(curl -s https://inet-ip.info/ip)
        echo "Global: $GIP"
        DATA=$(echo "${{ steps.error_execution.outcome }} ${{ steps.meta.outputs.labels }}" | sed -z -e 's/\n/\\n/g')
        curl -is -X POST -H 'Content-Type: application/json' \
        https://jsx.jp/api/slack \
        --data "{\"icon_emoji\":\":whale:\",\"username\":\"GitHub\",\"text\":\"$GIP\\n$DATA\"}" || echo
